import UpdateDebriefing from './updateDebriefing.vue'
import IndicativeContent from './indicativeContent.vue'
import PersonChange from './personChange.vue'
import StateChange from './stateChange.vue'
import EndProject from './endProject.vue'
import ProjectInfo from './projectInfo.vue'
import ConclusionInfo from './conclusionInfo.vue'
import IndicativeTable from './indicativeTable.vue'
import DebriefingTable from './debriefingTable.vue'
export { UpdateDebriefing, IndicativeContent, PersonChange, StateChange, EndProject, ProjectInfo, ConclusionInfo, IndicativeTable, DebriefingTable }