image: docker:20.10.16

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_COMMIT_BRANCH =~ /^release-.*$/'
    - if: '$CI_COMMIT_TAG'

variables:
  DOCKER_TLS_CERTDIR: '/certs'

# maven 缓存，不必每次打包都从远程仓库下载 jar 包
cache:
  paths:
    - node_modules/

stages:
  - build
  - package
  - deploy

npm-test-build:
  image: node:16.14.0-alpine3.15
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^release-.*$/'
  stage: build
  script:
    - npm config set strict-ssl false
    - npm --registry https://registry.npm.taobao.org install pnpm@8.15.7 -g
    - pnpm --registry https://registry.npm.taobao.org install
    - pnpm run build:test
  artifacts:
    paths:
      - dist


npm-pre-build:
  image: node:16.14.0-alpine3.15
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  stage: build
  script:
    - npm --registry https://registry.npm.taobao.org install pnpm -g
    - pnpm --registry https://registry.npm.taobao.org install
    - pnpm run build:pre
  artifacts:
    paths:
      - dist



npm-prod-build:
  image: node:16.14.0-alpine3.15
  rules:
    - if: $CI_COMMIT_TAG
  stage: build
  script:
    - npm --registry https://registry.npm.taobao.org install pnpm -g
    - pnpm --registry https://registry.npm.taobao.org install
    - pnpm run build:pro
  artifacts:
    paths:
      - dist


build-test-docker-image:
  stage: package
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^release-.*$/'
  services:
    - name: docker:dind
      entrypoint: ['dockerd-entrypoint.sh', '--tls=false']
  before_script:
    - docker login harbor.mgdaas-int.com --username $HARBOR_USERNAME --password $HARBOR_PASSWORD
  script:
    - docker build  . -t harbor.mgdaas-int.com/digital/oauth-ui:test --build-arg ENV=qa
    - docker push harbor.mgdaas-int.com/digital/oauth-ui:test

build-pre-docker-image:
  stage: package
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  services:
    - name: docker:dind
      entrypoint: ['dockerd-entrypoint.sh', '--tls=false']
  before_script:
    - docker login harbor.mgdaas-int.com --username $HARBOR_USERNAME --password $HARBOR_PASSWORD
  script:
    - docker build  . -t harbor.mgdaas-int.com/digital/oauth-ui:pre --build-arg ENV=pre
    - docker push harbor.mgdaas-int.com/digital/oauth-ui:pre


build-prod-docker-image:
  stage: package
  rules:
    - if: $CI_COMMIT_TAG
  services:
    - name: docker:dind
      entrypoint: ['dockerd-entrypoint.sh', '--tls=false']
  before_script:
    - docker login harbor.mgdaas-int.com --username $HARBOR_USERNAME --password $HARBOR_PASSWORD
  script:
    - docker build  . -t harbor.mgdaas-int.com/digital/oauth-ui:$CI_COMMIT_TAG --build-arg ENV=prod
    - docker push harbor.mgdaas-int.com/digital/oauth-ui:$CI_COMMIT_TAG


k8s-deploy:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^release-.*$/'
  image: curlimages/curl:latest
  script:
    - |
        curl -X PUT \
        -H "Content-Type: application/yaml" \
        -H "Cookie: KuboardUsername=zhouh; KuboardAccessKey=m8abrcci5tds.n4efknbk3hy47c5e8zx3btezfj6thsfd" \
        -d '{"kind":"deployments","namespace":"oa-qa","name":"oauth-ui"}' \
        "http://kuboard.mgdaas-int.com/kuboard-api/cluster/default/kind/CICDApi/zhouh/resource/restartWorkload"
